# Generated by Django 5.1.15 on 2026-05-26 23:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MosaicPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('filter_1', models.CharField(choices=[('grayscale', 'Grayscale'), ('sepia', 'Sepia'), ('blur', 'Blur'), ('contour', 'Contour'), ('sharpen', 'Sharpen'), ('emboss', 'Emboss'), ('edge_enhance', 'Edge Enhance'), ('smooth', 'Smooth')], max_length=30)),
                ('filter_2', models.CharField(choices=[('grayscale', 'Grayscale'), ('sepia', 'Sepia'), ('blur', 'Blur'), ('contour', 'Contour'), ('sharpen', 'Sharpen'), ('emboss', 'Emboss'), ('edge_enhance', 'Edge Enhance'), ('smooth', 'Smooth')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MosaicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixed_image', models.ImageField(blank=True, upload_to='mixed/%Y/%m/')),
                ('mosaic_dir', models.CharField(blank=True, max_length=255)),
                ('zip_file', models.FileField(blank=True, upload_to='mosaics/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='mosaico.mosaicpackage')),
            ],
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='originals/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mosaico.mosaicpackage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('package', 'order')},
            },
        ),
    ]
